language: python
python:
  - 2.6
  - 2.7
install:
  - pip install coveralls
  - pushd ~
  - git clone https://github.com/mottosso/pyblish.git
  - export PYTHONPATH=${PWD}/pyblish
  - popd
script:
  - python run_coverage.py
after_success:
  - coveralls
  on:
    python: 2.7